version: "3"
services:
  client:
    user: root
    restart: always
    build: 
      context: ./client
      args:
        BUILD_TIME: ''
        GIT_COMMIT: ''
    env_file:
      - ./envs/.env
    ports:
      - "80:80"
    healthcheck:
      test: curl --fail -s http://localhost:80/health || exit 1
    container_name: todo-client
  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/var/lib/mysql
    container_name: todo-db
  api:
    build: 
      context: ./server
      args:
        BUILD_TIME: ''
        GIT_COMMIT: ''
    user: root
    restart: always
    ports:
      - "8080:8080"
    healthcheck:
      test: curl --fail -s http://localhost:8080/health || exit 1
    depends_on:
      - db
    container_name: todo-api
volumes:
  node_modules:  
  mongodb-data:
    name: mongodb-data