version: "3"
services:
  client:
    build: 
      context: ./client
      dockerfile: ./client/Dockerfile
    ports:
      - "80:80"
    container_name: todo-client
  db:
    image: mongo
    ports:
      - "27017:27017"
    container_name: todo-db
  api:
    build: 
      context: ./server
      dockerfile: ./server/Dockerfile
    user: root
    command: >
      sh -c "npm i @nestjs/cli && npm run start:dev"
    ports:
      - "8080:8080"
    depends_on:
      - db
    container_name: todo-api
volumes:
  node_modules:  
  mongodb-data:
    name: mongodb-data